language: python
python:
    - '2.6'
    - '2.7'
    - '3.5'
install:
    - pip install --upgrade pytest coverage codecov
    - pip install .
script:
    - coverage run --source cylcutil -m py.test
after_success:
    - codecov
# deploy:
#   provider: pypi
#   user:
#   password:
#     secure: 
#   on:
#     tags: true
#     repo: ScottWales/cylcutil
#   distributions: "sdist bdist_wheel"
